# Generated by Django 3.2.2 on 2021-06-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz_inicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
