# Generated by Django 3.2.2 on 2021-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz_inicial', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
