# Generated by Django 3.2.2 on 2021-06-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfesoresApartado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='Cargo',
            new_name='Rol',
        ),
    ]
