# Generated by Django 3.2.2 on 2021-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfesoresApartado', '0002_rename_cargo_personal_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='Tipo_A',
        ),
        migrations.AlterField(
            model_name='personal',
            name='Rol',
            field=models.CharField(max_length=100),
        ),
    ]
