# Generated by Django 3.2.2 on 2021-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Nombre_A', models.CharField(max_length=25)),
                ('Apellido_PA', models.CharField(max_length=15)),
                ('Apellido_MA', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=30)),
                ('Calle', models.CharField(max_length=20)),
                ('Num_Int', models.IntegerField()),
                ('Num_Ext', models.IntegerField()),
                ('Colonia', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=30)),
                ('Municipio', models.CharField(max_length=30)),
                ('CP', models.IntegerField()),
                ('Posgrado', models.CharField(max_length=25)),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=1)),
                ('Telefono', models.IntegerField()),
                ('Tipo_A', models.CharField(max_length=10)),
                ('Estado_A', models.CharField(max_length=10)),
                ('Semestre', models.CharField(max_length=3)),
            ],
        ),
    ]
