# Generated by Django 3.2.2 on 2021-05-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_calificaciones'),
        ('Unidades_de_Aprendizaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Clave_M',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidades_de_Aprendizaje.unidad_de_aprendizaje'),
        ),
    ]
