# Generated by Django 3.2.2 on 2021-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='Rol',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
