# Generated by Django 3.2.2 on 2021-06-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades_de_Aprendizaje', '0002_alter_unidad_de_aprendizaje_posgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_de_aprendizaje',
            name='Posgrado',
            field=models.CharField(max_length=100),
        ),
    ]
