# Generated by Django 3.2.2 on 2021-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Boleta',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
