# Generated by Django 3.2.2 on 2021-06-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_colegio',
            name='Folio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
