# Generated by Django 3.2.2 on 2021-06-03 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfesoresApartado', '0001_initial'),
        ('AlumnosApartado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_Colegio',
            fields=[
                ('Folio', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Nombre_Tram', models.CharField(max_length=30)),
                ('Periodo', models.CharField(max_length=3)),
                ('Fecha', models.DateField()),
                ('Estatus', models.CharField(max_length=11)),
                ('Respuesta', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosApartado.alumno')),
                ('Num_Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfesoresApartado.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes_Comite',
            fields=[
                ('Clave_Comite', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Solicitud_Com', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Fecha', models.DateField()),
                ('Boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosApartado.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acta_alumno', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('CURP', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Titulo', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Constancia_ingles', models.FileField(upload_to='SistemaPosgrado/archivos/')),
                ('Boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosApartado.alumno')),
            ],
        ),
    ]
