# Generated by Django 3.2.2 on 2021-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfesoresApartado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contraseña', models.CharField(max_length=15)),
                ('Correo', models.ManyToManyField(to='ProfesoresApartado.Personal')),
            ],
        ),
    ]
